name: landuse_det

services:
  landuse_det:
    image: landuse_det
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - ./__landuse_cache__:/app/__landuse_cache__
